name: "Tempo Lints"
description: "Run Tempo ast-grep lint rules on your codebase"
author: "Stripe"

branding:
  icon: "check-circle"
  color: "purple"

inputs:
  language:
    description: "Language to lint: rust, typescript, or all"
    required: true
  path:
    description: "Path to scan (defaults to current directory)"
    required: false
    default: "."
  fail-on-error:
    description: "Fail the action if lint errors are found"
    required: false
    default: "true"
  exclude-rules:
    description: 'Comma-separated list of rule IDs to exclude (e.g., "no-dbg-macro,no-console-log")'
    required: false
    default: ""
  fix:
    description: "Apply auto-fixes where available"
    required: false
    default: "false"
  post-comment:
    description: "Post lint results as a PR comment"
    required: false
    default: "false"
  github-token:
    description: "GitHub token for posting PR comments (required if post-comment is true)"
    required: false
    default: ""

outputs:
  has-errors:
    description: "Whether any error-level issues were found"
    value: ${{ steps.run-lint.outputs.has_errors }}

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - name: Cache pnpm dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: tempo-lints-pnpm-${{ runner.os }}-${{ hashFiles(format('{0}/pnpm-lock.yaml', github.action_path)) }}
        restore-keys: |
          tempo-lints-pnpm-${{ runner.os }}-

    - name: Install tempo-lints dependencies
      shell: bash
      run: cd "${{ github.action_path }}" && pnpm install --frozen-lockfile

    - name: Run Tempo Lints
      id: run-lint
      shell: bash
      run: |
        # Build CLI args
        CLI_ARGS="${{ inputs.language }} ${{ inputs.path }} --github-action"

        if [ -n "${{ inputs.exclude-rules }}" ]; then
          CLI_ARGS="$CLI_ARGS --exclude ${{ inputs.exclude-rules }}"
        fi

        if [ "${{ inputs.fix }}" = "true" ]; then
          CLI_ARGS="$CLI_ARGS --fix"
        fi

        # Run lint with --github-action flag (outputs annotations and summary)
        set +e
        pnpm --dir "${{ github.action_path }}" exec tsx "${{ github.action_path }}/bin/tempo-lints.ts" $CLI_ARGS
        EXIT_CODE=$?
        set -e

        # Set outputs based on exit code
        HAS_ERRORS="false"
        if [ "$EXIT_CODE" != "0" ]; then
          HAS_ERRORS="true"
        fi

        echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
        echo "has_errors=$HAS_ERRORS" >> $GITHUB_OUTPUT

    - name: Post PR comment
      if: inputs.post-comment == 'true' && github.event_name == 'pull_request'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        if [ -z "$GITHUB_TOKEN" ]; then
          echo "::warning::github-token is required for posting PR comments"
          exit 0
        fi

        # Build CLI args for JSON output
        CLI_ARGS="${{ inputs.language }} ${{ inputs.path }} --json"

        if [ -n "${{ inputs.exclude-rules }}" ]; then
          CLI_ARGS="$CLI_ARGS --exclude ${{ inputs.exclude-rules }}"
        fi

        # Run lint with --json to get structured output for comment
        OUTPUT_FILE="${{ runner.temp }}/tempo-lints-comment.json"
        set +e
        pnpm --dir "${{ github.action_path }}" exec tsx "${{ github.action_path }}/bin/tempo-lints.ts" $CLI_ARGS > "$OUTPUT_FILE" 2>/dev/null
        set -e

        TOTAL_ISSUES=$(cat "$OUTPUT_FILE" | node -p "try { JSON.parse(require('fs').readFileSync(0,'utf8')).length } catch { 0 }" 2>/dev/null || echo "0")

        pnpm --dir "${{ github.action_path }}" exec tsx "${{ github.action_path }}/scripts/post-pr-comment.ts" \
          "$OUTPUT_FILE" \
          "$TOTAL_ISSUES" \
          "${{ github.repository }}" \
          "${{ github.event.pull_request.number }}"

    - name: Check for failures
      if: inputs.fail-on-error == 'true'
      shell: bash
      run: |
        EXIT_CODE="${{ steps.run-lint.outputs.exit_code }}"
        if [ "$EXIT_CODE" != "0" ]; then
          echo "::error::Lint errors found. Fix the issues above or set fail-on-error to false."
          exit 1
        fi
